### ISSUE TITLE
Error: failed to create new program: Program with such name already exists in the project

### ISSUE THREAD

**Issue by VirajVaitha123** [deta/deta-cli#84]
How do I delete a deta and redeploy?

**Comment by aavshr** [comment]
hi @VirajVaitha123 , you can use your dashboard (https://web.deta.sh) and delete your Micro from the `Settings` tab. 

To create a new Micro from existing Micro code, you can delete the `.deta` folder with `rm -r ./.deta` and then do `deta new` after the Micro has been deleted from your dashboard. 

I'm closing this issue here as it does not pertain to the cli. If you have further questions please use our slack/discord/intercom or send us an email.
